version: '3'
services:

  # The Application
  app:
    build:
      context: ./docker/
      dockerfile: app.dockerfile
    container_name: my_blog_app
    working_dir: /var/www
    volumes:
      - ./:/var/www/

  # The Web Server
  web:
    build:
      context: ./docker/
      dockerfile: web.dockerfile
    container_name: my_blog_web
    working_dir: /var/www
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:5.6
    container_name: my_blog_db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=my_blog"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=phucb1506"
      - "MYSQL_ROOT_PASSWORD=phucb1506"
    ports:
      - "3309:3306"

volumes:
  dbdata:
